'use strict';

const crypto=require('node:crypto');
let WebSocket;
function wsLib(){return WebSocket||(WebSocket=require('ws'))}
const WS_URL='wss://uniproxy.alice.yandex.net/uni.ws',ORIGIN='https://alice.yandex.ru',APP_ID='ru.yandex.web.desktop',APP_VERSION='1.0.281-home-static/alice-web/15',USER_AGENT='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36',FEATURES=['open_link','server_action','cloud_ui','show_promo','print_text_in_message_view'],MODELS={alice:'Alice AI (Yandex)','alice-ai':'Alice AI (Yandex)',yagpt:'YaGPT (Yandex)'};
class AliceError extends Error{constructor(code,message,status=502,retryable=false){super(message);this.name='AliceError';this.code=code;this.status=status;this.retryable=retryable}}
const id=()=>crypto.randomUUID(),textOf=c=>Array.isArray(c)?c.map(x=>typeof x==='string'?x:(x&&(x.type==='text'||x.type==='input_text')?String(x.text||''): '')).join(''):c==null?'':String(c);
const foldMessages=messages=>(messages||[]).map(m=>{const role=String(m?.role||'user')==='developer'?'system':String(m?.role||'user'),text=textOf(m?.content).trim();return text?role[0].toUpperCase()+role.slice(1)+': '+text:''}).filter(Boolean).join('\n');
function trimPrompt(prompt,limit=6000){const s=String(prompt||''),n=Math.max(1,Number(limit)||6000);if(s.length<=n)return s;if(n<=5)return s.slice(0,n);const mark='\n...\n',usable=n-mark.length,tail=Math.min(Math.max(1,Math.floor(n/8)),Math.floor(usable/2));return s.slice(0,usable-tail)+mark+s.slice(-tail)}
function normalizeCookieHeader(v){if(!v)return '';if(Array.isArray(v))return v.filter(x=>x&&typeof x.name==='string'&&typeof x.value==='string').map(x=>x.name+'='+x.value).join('; ');return String(v).replace(/[\r\n]/g,' ').trim()}
function loadCookieHeader(v){if(!v)return '';if(typeof v==='string')return normalizeCookieHeader(v);if(typeof v.cookieHeader==='string')return normalizeCookieHeader(v.cookieHeader);return normalizeCookieHeader(Array.isArray(v.cookies)?v.cookies:v)}
function extractText(d){const r=d?.payload?.response;for(const x of r?.directives||[])if(typeof x?.payload?.text==='string'&&x.payload.text.trim())return x.payload.text;if(typeof r?.card?.text==='string'&&r.card.text.trim())return r.card.text;for(const u of r?.chat_dialog_update||[])for(const m of u?.add_message_request?.messages||[])if(typeof m?.content?.plain_response_text==='string'&&m.content.plain_response_text.trim())return m.content.plain_response_text;return ''}
const placeholder=s=>/^(одну секунду|секунду|подождите|подумаю)[.!?]*$/i.test(String(s||'').trim());
class AliceClient{
constructor(o={}){this.url=o.url||WS_URL;this.cookie=normalizeCookieHeader(o.cookie);this.timeout=Number(o.timeoutMs||60000);this.maxChars=Number(o.maxPromptChars||6000);this.appVersion=o.appVersion||APP_VERSION;this.userAgent=o.userAgent||USER_AGENT;this.ws=null;this.seq=1;this.uuid=id();this.lastRequestId=null;this.stackSessionId=null;this.frames=[];this.pending=[];this.sync=null}
get authenticated(){return !!this.cookie}
close(){if(this.sync)this.sync.reject(new AliceError('CLOSED','Alice connection closed',502,true));this.sync=null;for(const p of this.pending)p.reject(new AliceError('CLOSED','Alice connection closed',502,true));this.pending=[];this.frames=[];if(this.ws)try{this.ws.close()}catch{}this.ws=null}
deliver(v){const p=this.pending.shift();if(p)(v instanceof Error?p.reject(v):p.resolve(v));else this.frames.push(v)}
nextFrame(ms=30000){if(this.frames.length)return Promise.resolve(this.frames.shift());return new Promise((resolve,reject)=>{const p={resolve,reject};const t=setTimeout(()=>{const i=this.pending.indexOf(p);if(i>=0)this.pending.splice(i,1);reject(new AliceError('UPSTREAM_TIMEOUT','Alice did not answer in time',504,true))},ms);this.pending.push({resolve:x=>{clearTimeout(t);resolve(x)},reject:e=>{clearTimeout(t);reject(e)}})})}
send(o){return new Promise((resolve,reject)=>{if(!this.ws||this.ws.readyState!==wsLib().OPEN)return reject(new AliceError('CONNECT_FAILED','Alice socket is not connected',502,true));this.ws.send(JSON.stringify(o),e=>e?reject(e):resolve())})}
async connect(){if(this.ws&&this.ws.readyState===wsLib().OPEN)return;this.close();this.frames=[];this.pending=[];this.uuid=id();this.seq=1;this.lastRequestId=null;this.stackSessionId=null;const WS=wsLib(),headers={'User-Agent':this.userAgent};if(this.cookie)headers.Cookie=this.cookie;await new Promise((resolve,reject)=>{const ws=new WS(this.url,{origin:ORIGIN,headers,handshakeTimeout:this.timeout,perMessageDeflate:false});this.ws=ws;let done=false;const fail=e=>{if(!done){done=true;reject(e)}};ws.on('message',d=>this.onMessage(d));ws.once('error',e=>fail(new AliceError('CONNECT_FAILED','Alice connection failed: '+(e.message||e),502,true)));ws.once('close',()=>{if(!done)fail(new AliceError('CONNECT_DROPPED','Alice closed the connection',502,true));this.ws=null;this.deliver(new AliceError('CONNECT_DROPPED','Alice closed the connection',502,true))});ws.once('open',async()=>{try{const msg={event:{header:{namespace:'System',name:'SynchronizeState',messageId:id(),seqNumber:1},payload:{auth_token:id(),uuid:this.uuid,vins:{application:{app_id:APP_ID,platform:'windows'}}}}};this.sync={};this.sync.promise=new Promise((r,j)=>{this.sync.resolve=r;this.sync.reject=j});const timer=setTimeout(()=>this.sync?.reject(new AliceError('HANDSHAKE_TIMEOUT','Alice handshake timed out',504,true)),Math.min(this.timeout,20000));await this.send(msg);await this.sync.promise;clearTimeout(timer);this.sync=null;if(!done){done=true;resolve()}}catch(e){this.sync=null;fail(e instanceof AliceError?e:new AliceError('HANDSHAKE_FAILED',String(e),502,true))}})})}
onMessage(data){let root;try{root=JSON.parse(data.toString())}catch{return}const d=root?.directive,h=d?.header||{},n=h.name,ns=h.namespace;if(ns==='System'&&n==='Ping')return this.send({event:{header:{namespace:'System',name:'Pong',messageId:id(),refMessageId:h.messageId},payload:{}}}).catch(()=>{});if(ns==='System'&&n==='SynchronizeStateResponse')return this.sync?.resolve();if(ns==='System'&&n==='InvalidAuth')return this.deliver(new AliceError('AUTH_REJECTED','Yandex rejected the supplied Alice session',401,false));if(ns==='System'&&n==='GoAway')return this.deliver(new AliceError('GOAWAY','Alice closed the session',502,true));if(ns==='System'&&n==='EventException')return this.deliver(new AliceError('UPSTREAM_ERROR',String(d?.payload?.error?.message||'Alice upstream error')));this.deliver(d)}
textInput(event,prev=null){const requestId=id();this.seq++;const payload={application:{app_id:APP_ID,app_version:this.appVersion,platform:'windows',os_version:this.userAgent.toLowerCase(),uuid:this.uuid,device_id:this.uuid,lang:'ru',client_time:new Date().toISOString().replace(/[-:]/g,'').slice(0,15),timezone:'Europe/Moscow',timestamp:String(Math.floor(Date.now()/1000))},header:{prev_req_id:prev,sequence_number:null,request_id:requestId,dialog_id:'',dialog_type:1},request:{event,voice_session:false,experiments:[],uniproxy_options:{background_response_streaming_options:{},dialog_options:{}},additional_options:{bass_options:{user_agent:this.userAgent,screen_scale_factor:1},origin_domain:'alice.yandex.ru',supported_features:FEATURES,unsupported_features:[]}},location:{},reset_session:false,environment_state:{endpoints:[{id:'alice.yandex.ru',capabilities:[]}]},format:'audio/ogg;codecs=opus',mime:'audio/webm;codecs=opus',topic:'desktopgeneral',punctuation:false};return{event:{header:{namespace:'Vins',name:'TextInput',messageId:id(),seqNumber:this.seq},payload},requestId}}
async ask(prompt){const text=trimPrompt(prompt,this.maxChars);if(!text.trim())throw new AliceError('EMPTY_PROMPT','Prompt is empty',400,false);await this.connect();this.frames=[];this.pending=[];let r=this.textInput({type:'text_input',text},null);this.lastRequestId=r.requestId;this.stackSessionId=r.requestId;await this.send(r.event);let held='';for(let i=0;i<24;i++){const d=await this.nextFrame(Math.min(this.timeout,30000)),t=extractText(d);if(t){if(placeholder(t))held||=(t);else return{text:t,placeholder:held,authenticated:this.authenticated}}r=this.textInput({type:'server_action',name:'@@mm_stack_engine_get_next',payload:{'@recovery_params':{},'@request_id':this.lastRequestId,stack_session_id:this.stackSessionId||this.lastRequestId,'@scenario_name':'Dialogovo',stack_product_scenario_name:'dialogovo'}},this.lastRequestId);this.lastRequestId=r.requestId;await new Promise(x=>setTimeout(x,50));await this.send(r.event)}throw new AliceError('EMPTY_ANSWER','Alice produced no final answer'+(held?': '+held:''),502,true)}
}
module.exports={AliceClient,AliceError,MODEL_NAMES:MODELS,foldMessages,textOf,trimPrompt,normalizeCookieHeader,loadCookieHeader};
