'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),cp=require('node:child_process'),readline=require('node:readline');
let WebSocket;function ws(){return WebSocket||(WebSocket=require('ws'))}
const out=path.resolve(process.env.ALICE_AUTH_PATH||'alice-auth.json'),port=Number(process.env.ALICE_CDP_PORT||9222),profile=process.env.ALICE_CHROME_PROFILE||path.join(os.tmpdir(),'freealice-chrome-profile');
function chromePath(){if(process.env.ALICE_CHROME_PATH)return process.env.ALICE_CHROME_PATH;const c=process.platform==='win32'?[process.env.LOCALAPPDATA&&path.join(process.env.LOCALAPPDATA,'Google/Chrome/Application/chrome.exe'),'chrome.exe']:process.platform==='darwin'?['/Applications/Google Chrome.app/Contents/MacOS/Google Chrome','/Applications/Chromium.app/Contents/MacOS/Chromium']:['google-chrome','google-chrome-stable','chromium','chromium-browser'];return c.find(x=>x&&(path.isAbsolute(x)?fs.existsSync(x):true))||''}
async function json(url){const r=await fetch(url);if(!r.ok)throw new Error(url+' -> HTTP '+r.status);return r.json()}
async function wait(){for(let i=0;i<30;i++){try{return await json('http://127.0.0.1:'+port+'/json/list')}catch{await new Promise(r=>setTimeout(r,500))}}throw new Error('Chrome DevTools did not open')}
function cdp(url){const C=ws(),s=new C(url);let n=0;const p=new Map();s.on('message',d=>{try{const m=JSON.parse(d.toString()),x=p.get(m.id);if(!x)return;p.delete(m.id);m.error?x.reject(new Error(m.error.message||'CDP error')):x.resolve(m.result)}catch{}});const open=new Promise((r,j)=>{s.once('open',r);s.once('error',j)});return{call:async(method,params={})=>{await open;const id=++n;return new Promise((resolve,reject)=>{p.set(id,{resolve,reject});s.send(JSON.stringify({id,method,params}))})},close:()=>{try{s.close()}catch{}}}}
function ask(q){const r=readline.createInterface({input:process.stdin,output:process.stdout});return new Promise(x=>r.question(q,a=>{r.close();x(a)}))}
const allowed=d=>{d=String(d||'').toLowerCase();return d==='yandex.ru'||d.endsWith('.yandex.ru')||d==='ya.ru'||d.endsWith('.ya.ru')};
(async()=>{const chrome=chromePath();if(!chrome)throw new Error('Chrome/Chromium not found; set ALICE_CHROME_PATH or use auth:import');fs.mkdirSync(profile,{recursive:true});const child=cp.spawn(chrome,['--remote-debugging-port='+port,'--user-data-dir='+profile,'--no-first-run','--no-default-browser-check','https://alice.yandex.ru/'],{stdio:'ignore',detached:true});child.unref();const pages=await wait(),page=pages.find(x=>x.type==='page'&&/alice\.yandex\.ru/i.test(x.url))||pages.find(x=>x.type==='page');if(!page?.webSocketDebuggerUrl)throw new Error('Alice page not found');console.log('Chrome opened with an isolated profile. Complete Yandex ID login if needed.');await ask('Press Enter after login: ');const c=cdp(page.webSocketDebuggerUrl);try{const r=await c.call('Network.getAllCookies');const cookies=(r.cookies||[]).filter(x=>allowed(x.domain)).map(x=>({name:x.name,value:x.value,domain:x.domain,path:x.path,secure:x.secure,httpOnly:x.httpOnly,expirationDate:x.expires}));if(!cookies.length)throw new Error('No Yandex cookies found');fs.writeFileSync(out,JSON.stringify({version:1,created_at:new Date().toISOString(),cookies},null,2)+'\n',{mode:0o600});try{fs.chmodSync(out,0o600)}catch{}console.log('Saved '+cookies.length+' Yandex cookies to '+out)}finally{c.close()}})().catch(e=>{console.error('Auth failed: '+e.message);process.exit(1)});
